### ISSUE TITLE
Is it possible to update bookmarks with image files?

### ISSUE THREAD

**Issue by geniuszty** [doesdev/docxmarks#1]
something like this:

new DocxMarks(testDocxIn).update('BookMarkName', imageFile);

or

new DocxMarks(testDocxIn).update('BookMarkName', 'http://www.github.com/logo.png');

**Comment by doesdev** [comment]
I think you'll want to use [docxtemplater](https://github.com/open-xml-templating/docxtemplater) for this. It gives you allot more options for content. This library is really narrow in what it supports because it's quite ignorant to the OOXML specification, it's just using some simple regexes for the bookmarks. In order to support images we would need to be properly parsing and handling the OOXML elements in the docx file.
